import "./globals.scss";

import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

const outfit = Outfit({
  weight: "400",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
